### ISSUE TITLE
Issue with municipality inventory import

### ISSUE THREAD

**Issue by micastre** [ValValetl/SMMT#1]
Dear Valentin, 
First of all: thanks for developing such a useful package for the scientific community!

I just wanted to use it for the first time and I'm having an issue with the .xml data import from the municipality inventory. When I run the following code (following the example on the SMMT manual page: https://smmt.valentinknechtl.ch/articles/manual.html#setup), I get an error message:

```
library(SMMT)
path_inventory_xml <- download_municipality_inventory(path = getwd())

```
The error message is "Error in if (!copy_success) stop(paste0("XML File already exists at target (",  : 
the condition has length > 1"

Despite the error message, an .xml-file appears in the working directory, and I can get into R with the alternative option that is indicated on the webpage, in my case:

`file_path_inventory_xml <- "path/to/eCH0071_230101.xml"`

However, when I then want to generate the mutations_object through the following line of code
`mutations_object <- import_CH_municipality_inventory(file_path = file_path_inventory_xml)`
I get another error message: "Error: XML content does not seem to be XML: ''

I'm a bit lost concerning what I'm doing wrong or what the issue is here and help would be much appreciated. 
I'm using R version 4.2.2 ((2022-10-31 ucrt) -- "Innocent and Trusting") on a Windows 64-bit machine if that is of any help.
Thanks a lot,
Michael

**Comment by ValValetl** [comment]
Hi Michael

Thank you for using SMMT and for the detailed bug report. I will have a look at it and come back to your issue soon.

If you have further questions, etc. do not hesitate to reach out.

Grüsse
Valentin

**Comment by micastre** [comment]
Dear Valentin,
Thanks a lot for your reply. I just wanted to quickly check in with you, if you already had time to check out the issue. I absolutely do not want to rush you - it's simply to know for me whether for the current version of a study I'm working on and which has a deadline soon, I just resort to the "simple" merge (and hence drop all merged municipalities) or whether I'll wait, because you're close to fixing the issue. 
In any case, I would like to use the tool for a further iteration of the study :)
Danke und Grüsse,
Michael

**Comment by ValValetl** [comment]
Hi Michael

sorry for the long delay.

I just started to look at the issue and solved the first part with the download_municipality_inventory() .

However, I cannot reproduce the second bug. My code:

`library(SMMT)`
`path_to_inventory <- download_municipality_inventory(path = getwd())`
`municipality_inventory <- import_CH_municipality_inventory(file_path = path_to_inventory)`



Could you tell me your XML package version? mine is 3.99-0.14

* Also, could you try to use the full path (e.g. "C:/full/path/to/xml.xml")
* Furthermore, be sure that you use the correct path to the xml. In your case, this should be `file_path_inventory_xml  <- file.path(getwd(), "eCH0071_230101.xml")`


I am happy to provide further help if needed :)

Liebe Grüsse
Valentin

**Comment by ValValetl** [comment]
btw. to get the SMMT package with the first fix included, use the following lines of code:
`library(devtools)`
`devtools::install_github("ValValetl/SMMT")`

**Comment by micastre** [comment]
Dear Valentin,
Thanks a lot for checking and fixing these bugs. It worked perfectly now and the second error did not reoccur for me neither. I very much assume that the issue was that prior to your first bug fix, the downloaded xml file was not correctly downloaded/was missing information and couldn't be read in. But now with your fix of the first bug, I also did not get the second bug anymore (I also updated my XML-package to the current version prior to trying out the fixed SMMT version, so that might also have done the trick).
In any case, what's most important, is that the error does not occur anymore and that I managed to load the mutations_object.
I'll now explore the powers of your magic tool ;)
Thanks a lot again and all the best,
Michael

**Comment by ValValetl** [comment]
Hei Michael

Great to hear that it works.

It is a bit a side note: But for the further development, I would be really interesting to know for me what kind of data sets you are working with and what kind of field you are in. Would you mind to tell me? You could also write an email (see my mail on CRAN) if you like.

Have a nice evening
Valentin
